affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/pci-0302_10de.present
          operator: In
          values:
          - "true"
gfd:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: feature.node.kubernetes.io/pci-0302_10de.present
            operator: In
            values:
            - "true"
  enabled: true
  tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
    value: "true"
mps:
  enabled: false
nfd:
  enabled: false
tolerations:
- effect: NoSchedule
  key: nvidia.com/gpu
  operator: Equal
  value: "true"
